apiVersion: v1
kind: Service
metadata:
  name: shah-service
spec:
  selector:
    app: shah
  ports:
    - protocol: TCP
      port: 80  # Port exposed outside the cluster
      targetPort: 8080  # Port your application listens on inside the container
  type: LoadBalancer  # Type of service (LoadBalancer for external access)
