name: "Build_TF_Plan"
on:
  push:
    paths:
      - terraform/**

jobs:
  build-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: Setup Terraform via terraform cloud
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

      - name: Terraform
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate
          terraform plan