name: "Build_TF_Plan"
on:
  push:
    paths:
      - terraform/**

jobs:
  build-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: Setup Terraform via terraform cloud
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

      - name: Go to terraform
        run: cd terraform

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
      #   continue-on-error: true

      # - name: Terraform Plan Status
      #   if: steps.plan.outcome == 'failure'
      #   run: exit 1