name: "Build_TF_Plan"
on:
  push:

jobs:
  build-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - uses: azure/setup-kubectl@v3
        id: install

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: 'eu-central-1'
        
      - name: Setup Terraform via terraform cloud
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

      - name: Terraform
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate
          terraform plan
      
      # - name: Configure AWS credentials and kubectl
      #   run: |
      #     aws eks --region eu-central-1 update-kubeconfig --name shah